### ISSUE TITLE
download

### ISSUE THREAD

**Issue by liquidmetal2** [RIAEvangelist/insane-alarm#1]
Hi I had purchased insane alarm vide order 199692275 on 20th Feb 2016. In the interim due to problems with my MBP, I seem to have lost the zip/installer file and not able to d/load from the site (appears to be greyed out). 
your help required

Thanks

**Comment by RIAEvangelist** [comment]
@liquidmetal2 
[download here](https://github.com/RIAEvangelist/insane-alarm/releases)
